### ISSUE TITLE
Substitute operator in substitute.nvim is not working

### ISSUE THREAD

**Issue by yutkat** [XXiaoA/ns-textobject.nvim#3]
I am trying to use this operator(https://github.com/gbprod/substitute.nvim) in combination with the text object `iq` but it does not work.

I feel like the processing of substitute operator is stopped inside this function.
https://github.com/XXiaoA/ns-textobject.nvim/blob/0532dce31b14b9140c8be55df2e2270c413703bf/lua/ns-textobject/init.lua#L26

**Comment by XXiaoA** [comment]
Hi @yutkat ! 
First of all, I feel sorry I cannot reply you at first time due to my midterm exam.

I've found this problem for a long time while I was using nvim-surround(ns for short). When I press `ysiq`, the "action" stopped. Now ns-textobject using a modified version of `get_nearest_selections` from ns. Therefore, it is probably a bug of ns. I will figure out it ASAP in this weekend... or at least try to.

**Comment by XXiaoA** [comment]
It seems that this problem case by

https://github.com/kylechui/nvim-surround/blob/87839e18d3953eb8cebd23a007183fd6c48863b5/lua/nvim-surround/config.lua#L377

And if I guess right, the final source is this function

https://github.com/kylechui/nvim-surround/blob/87839e18d3953eb8cebd23a007183fd6c48863b5/lua/nvim-surround/config.lua#L288

At last, hey @kylechui !
I have to turn to you for help now.

**Comment by XXiaoA** [comment]
According to my test, this line caused the bug. However, I don't know that 's why. :disappointed: 

https://github.com/kylechui/nvim-surround/blob/main/lua/nvim-surround/buffer.lua#L138

**Comment by kylechui** [comment]
> According to my test, this line caused the bug. However, I don't know that 's why. disappointed
> 
> https://github.com/kylechui/nvim-surround/blob/main/lua/nvim-surround/buffer.lua#L138

Hi there, `iq` is not a built-in motion so this line will surely do nothing. You would need to define the motion somewhere using `onoremap` or something to that effect.

**Comment by kylechui** [comment]
Ok I think I see the issue? You seem to be calling my `delete` functions in your `get_nearest_selections` function for some reason. I would suggest you refactor to use my new `config.get_selection` function, and that way you can get motions. The error arises from Neovim blocking the command from running because it thinks you are modifying the buffer.

**Comment by XXiaoA** [comment]
> Ok I think I see the issue? You seem to be calling my `delete` functions in your `get_nearest_selections` function for some reason. I would suggest you refactor to use my new `config.get_selection` function, and that way you can get selections from motions. The error arises from Neovim blocking the command from running because it thinks you are modifying the buffer.

I've tried `config.get_selection` and the bug only appears if I used `{ motion = "something" }` as a parameter. So I suppose the bug is cause by the `motion.get_selection`

**Comment by kylechui** [comment]
Try using `config.get_selection({ motion = "a" .. c })`. However note that this returns a singular selection, instead of a pair of selections. So you would need to convert that into a pair of selections to use `filter_selections_list`. But then I think that it would work. I am currently busy with preparing for my final exams, but I might take a look over break if you're unable to figure it out.

**Comment by XXiaoA** [comment]
> Try using `config.get_selection({ motion = "a" .. c })`. However note that this returns a singular selection, instead of a pair of selections. So you would need to convert that into a pair of selections to use `filter_selections_list`. But then I think that it would work. I am currently busy with preparing for my final exams, but I might take a look over break if you're unable to figure it out.

Yeah, I used `config.get_selection({ motion = "a" .. c })`
 . But the action still stopped. Umm, you can figure out more after the exam. Wish you success in the exam!

**Comment by XXiaoA** [comment]
> According to my test, this line caused the bug. However, I don't know that 's why. 😞
> 
> https://github.com/kylechui/nvim-surround/blob/6b45fbffdabb2d8cd80d310006c92e59cec8fd74/lua/nvim-surround/buffer.lua#L142

After removing this line, we can use "ns-textobject" well on user operations. Because user operations need set `vim.go.operatorfunc` but it be reset by this line to get motion selection. I'll push a fix ASAP.

**Comment by XXiaoA** [comment]
I think everything works well now, please update the plugin. Feel free to reopen this issue if need @yutkat

**Comment by yutkat** [comment]
I was able to confirm that it works properly. Thank you very much :smile:
